name: pull-request-audit

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/hbba_lite

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: foxy

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgecode-dev

      - name: Compile packages in ROS workspace
        working-directory: catkin_ws
        run: |
          source /opt/ros/noetic/setup.bash
          colcon build

      - name: Run tests
        working-directory: catkin_ws
        run: |
          source /opt/ros/foxy/setup.bash
          colcon test --packages-up-to hbba_lite
          colcon test-result --all --verbose
