name: pull-request-audit

on:
  push:
    branches: [ros2]

  pull_request:
    branches: [ros2]

  workflow_dispatch:
    branches: [ros2]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: colcon_ws/src/hbba_lite

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgecode-dev

      - name: Compile packages in ROS workspace
        working-directory: colcon_ws
        run: |
          source /opt/ros/humble/setup.bash
          colcon build

      - name: Run tests
        working-directory: colcon_ws
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-up-to hbba_lite
          colcon test-result --all --verbose
